### ISSUE TITLE
Support kotlin for Streetcomplete endpoint

### ISSUE THREAD

**Issue by westnordost** [ENT8R/blacklistr#19]
After the migration of quests in Streetcomplete to Kotlin, unfortunately the endpoint does not work anymore :-(

It now looks like this (commented out what is may or may not be there / is optional)
```kotlin
override val enabledForCountries/* : Countries*/ /* get() */ = Countries.noneExcept(
        // all of Northern and Western Europe, most of Central Europe, some of Southern Europe
        "NO","SE","FI","IS","DK",
// etc...
)
```
So, the most future proof method would be to look for the first `Countries.` after `override val enabledForCountries` to read either `noneExcept` or `allExcept`, then look for the first `"` and parse the list of country codes as usual until the first `)` that is not in a comment.

**Comment by ENT8R** [comment]
Thank you for pointing this out. I have not thought about this yet...
Will do this within the next days

**Comment by ENT8R** [comment]
So, this should be fixed now...
Nevertheless all comments are now removed when specifying it directly through this endpoint, because the regular expression would not work otherwise... Maybe I will find a better solution for that in the future.

Another **breaking change** is that the endpoint at https://ent8r.github.io/blacklistr/?java=housenumber/AddHousenumber.kt has been renamed to  https://ent8r.github.io/blacklistr/?streetcomplete=housenumber/AddHousenumber.kt
Which makes a little bit more sense IMO.

**Comment by ENT8R** [comment]
@rugk Are there also links in the Wiki which need to be updated now?

**Comment by westnordost** [comment]
Ok I will update the links in my current Kotlin refactor.

Yes, it is still ongoing and it will let the wet dreams of MVC fans come true!! (from Bundle to proper typesafe and nullsafe model classes)
