### ISSUE TITLE
Link for StreetComplete does not work

### ISSUE THREAD

**Issue by rugk** [ENT8R/blacklistr#20]
I wana target this:
https://github.com/westnordost/StreetComplete/pull/1628/files#diff-17aac284c3410c5985409eb090dd1263R18-R20

But this link
https://ent8r.github.io/blacklistr/?streetcomplete=postbox_ref/AddPostboxRef.kt

Does not work and shows me the error
> TypeError: This file is not valid because it contains no black- or whitelist!

in Firefox 72

---

Also, is the `?java` endpoint still valid? Still used in OSM wiki.

**Comment by ENT8R** [comment]
> Also, is the `?java` endpoint still valid? Still used in OSM wiki.

No, I renamed this endpoint from `java=*` to `streetcomplete=*` a while ago when all quests where converted from Java to Kotlin. I wasn't sure whether the old links/endpoints were still in use, but I thought I looked into the wiki back then and couldn't find any link... 🤷

**Comment by ENT8R** [comment]
The link did not work because there were some unnoticed changes to the structure of a quest of StreetComplete, so the regular expression did not work anymore...
But this is now fixed with https://github.com/ENT8R/blacklistr/commit/d71758c4165b9fcdb10e1aefa4542479e6e8c02e
Thank you for making me aware of this bug 👍
