### ISSUE TITLE
Checkbox to toggle display of country borders

### ISSUE THREAD

**Issue by rugk** [ENT8R/blacklistr#3]
It is really funny to see these, and also useful for StreetComplete/technical aspects, but for Wiki visitors (see https://github.com/ENT8R/blacklistr/issues/2) it is not that useful.
So maybe just add a toggle, so you can hide these.

**Comment by rugk** [comment]
Ah, okay, I see what you did. Indeed I talked about the borders, but actually I meant the whole "custom area" (also the colored part on the oceans and so on, e.g.). I admit I have described that a bit imprecisely. 😇

So for the screenshots I just want a simple worldwide map in the background, where only the countries (and maybe islands in a bigger way) are displayed. Because non-technical people do not get what these big areas around countries (in the ocean and so on) mean.
So do you get what I want?

It's basically a simple "Atlas view" with just some countries colored.

**Comment by ENT8R** [comment]
Yes I know... This might be a littler bigger problem... The boundaries of the countries depend on [this file](https://github.com/westnordost/StreetComplete/blob/master/res/countryBoundaries.osm) by StreetComplete/JOSM. It is the best file I found so far, because it contains even the substates of the USA, India and China... All other files I found looked better on the map but they hadn't the substates...
This is basically what I asked for in https://github.com/westnordost/StreetComplete/pull/824#issuecomment-362796135
But maybe I can implement a switch between the currently used file and a file which contains only countries and no substates...

**Comment by rugk** [comment]
Ah, that is the issue, I see.

**Comment by ENT8R** [comment]
I think that this issue can not be fixed... The file used by SC/JOSM is the best that exists...
Is it OK for you? I mean not all borders are displayed... Only those who were specified.

**Comment by westnordost** [comment]
It'd be by me

**Comment by rugk** [comment]
Strange, that such a file cannot be found, but if it's not possible, it's not possible. Either mark it as "help wanted" so when one finds such a file, they can comment here, or just close it.

**Comment by ENT8R** [comment]
I did some search again and I still could not find a proper file. But as it is the same file as SC uses, it might not be such a huge problem, because then you can see directly where exactly it is enabled or disabled in the app...
So I will close this as there is probably no file that fits our needs...
